//ERROR NUMS 
#define  ERR_CODE_NOT_ENOUGH_ARGUMENTS  -1
#define  ERR_CODE_TOO_MANY_ARGUMENTS  -2
#define  FAILAD_TO_OPEN_FILE -3 
#define  NOT_VALID_INPUT -4
#define  MEMORY_ALLOCATION_FAILURE -5
#define  FAILAD_TO_CLOSE_FILE -5
///
#define  MAX_LINE_LEN  50

//#define MAX_LEN_OF_FOREST_STRING=